# Generated by Django 5.2.17 on 2026-09-29 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which shop this employee works at. Left blank until an admin assigns it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='branches.branch'),
        ),
    ]
