# Generated by Django 5.2.17 on 2026-09-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('QRPH', 'QR Ph'), ('GCASH', 'GCash'), ('CARD', 'Card'), ('OTHER', 'Other')], default='CASH', max_length=20),
        ),
    ]
