# Generated by Django 5.2.17 on 2026-09-30 05:03

from decimal import Decimal
from django.db import migrations, models
from django.db.models import Sum


def backfill_existing_delivery_totals(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    OrderItem = apps.get_model('orders', 'OrderItem')
    delivery_fee = Decimal('100.00')
    for order in Order.objects.all().iterator():
        subtotal = OrderItem.objects.filter(order_id=order.pk).aggregate(total=Sum('subtotal'))['total'] or Decimal('0.00')
        Order.objects.filter(pk=order.pk).update(
            fulfillment_method='DELIVERY',
            delivery_fee=delivery_fee,
            total_amount=subtotal + delivery_fee,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_method',
            field=models.CharField(choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], default='DELIVERY', max_length=12),
        ),
        migrations.RunPython(backfill_existing_delivery_totals, migrations.RunPython.noop),
    ]
