# Generated by Django 5.2.17 on 2026-09-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_address_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Order Placed'), ('DESIGNING', 'Designing'), ('PRINTING', 'Printing'), ('READY', 'Ready for Pickup'), ('PICKED_UP', 'Order Picked Up'), ('DELIVERED', 'Order Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLACED', max_length=20),
        ),
    ]
