from django.urls import path

from .views import (
    AdminCustomerDetailView,
    AdminCustomerListView,
    AdminNotificationsView,
    CurrentUserProfileView,
    CustomerAddressesView,
    CustomerNotificationsView,
    CustomerProfileView,
    CustomerSignupView,
    EmployeeCustomersView,
    EmployeeDashboardView,
    EmployeeDetailView,
    EmployeeListCreateView,
    EmployeeNotificationsView,
    LoginView,
    PasswordChangeView,
    ResendLoginCodeView,
    VerifyLoginView,
    VerifyPasswordView,
)

urlpatterns = [
    path('auth/login/', LoginView.as_view(), name='login'),
    path('auth/password/change/', PasswordChangeView.as_view(), name='password-change'),
    path('auth/password/verify/', VerifyPasswordView.as_view(), name='password-verify'),
    path('auth/login/verify/', VerifyLoginView.as_view(), name='login-verify'),
    path('auth/login/resend/', ResendLoginCodeView.as_view(), name='login-resend'),
    path('customers/signup/', CustomerSignupView.as_view(), name='customer-signup'),
    path('customers/me/', CustomerProfileView.as_view(), name='customer-profile'),
    path('users/me/', CurrentUserProfileView.as_view(), name='current-user-profile'),
    path('customers/addresses/', CustomerAddressesView.as_view(), name='customer-addresses'),
    path('customers/admin/', AdminCustomerListView.as_view(), name='admin-customers'),
    path('customers/admin/<int:pk>/', AdminCustomerDetailView.as_view(), name='admin-customer-detail'),
    path('notifications/customers/', CustomerNotificationsView.as_view(), name='customer-notifications'),
    path('notifications/admin/', AdminNotificationsView.as_view(), name='admin-notifications'),
    path('employees/', EmployeeListCreateView.as_view(), name='employee-list-create'),
    path('employees/<int:pk>/', EmployeeDetailView.as_view(), name='employee-detail'),
    path('employees/dashboard/', EmployeeDashboardView.as_view(), name='employee-dashboard'),
    path('employees/customers/', EmployeeCustomersView.as_view(), name='employee-customers'),
    path('employees/notifications/', EmployeeNotificationsView.as_view(), name='employee-notifications'),
]
